### ISSUE TITLE
.get_conversion_constant_sequence

### ISSUE THREAD

**Issue by edzer** [edzer/units#12]
in `.get_conversion_constant` I had to uncomment the call to `.get_conversion_constant_sequence`, otherwise I get this:
```
> library(units)
> x = make_unit("m")
> y = make_unit("s")
> x + x * y
2 m
```
@mailund repair, or remove?

**Comment by mailund** [comment]
This is a bug in `.get_conversion_constant_sequence`. It only checks that we get through all elements in the second sequence, not that we can convert all in the first. I will fix the bug.
