### ISSUE TITLE
sort out udunits calender and R's calender

### ISSUE THREAD

**Issue by edzer** [edzer/units#17]
e.g. how to convert from `POSIXct` or `Date` to a `udunits` value. See also [here](https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/CDM/CalendarDateTime.html). 

The question is whether udunits calender has additional value to R:
```
> d = make_units("days since 1970-01-01")
> as.numeric(as.Date("1971-01-01")) * d
365 (days since 1970-01-01)
> d * as.Date("1974-01-01")
1461 (days since 1970-01-01)
Warning message:
Incompatible methods ("Ops.units", "Ops.Date") for "*" 
```
For this particular case, I think the warning message could disappear, since both have identical units.

**Comment by edzer** [comment]
Seems like [RNetCDF](https://github.com/mjwoods/RNetCDF/blob/master/DESCRIPTION) has sorted this out; need to check with @mjwoods

**Comment by mjwoods** [comment]
RNetCDF may do what you want. For example:

```r
> library(RNetCDF)
> utinvcal.nc("hours since 1900-01-01 00:00:00 +01:00", ISOdatetime(1900,1,1,5,25,0,tz="UTC"))
[1] 6.416667
```

**Comment by edzer** [comment]
Thanks - the examples helped; things turned out to be _much_ easier than I thought!
