### ISSUE TITLE
Defining conversion for custom units

### ISSUE THREAD

**Issue by grpaulfr** [edzer/units#20]
I really like this package, it is very useful. I already had the issue in my collaborations that conversion between units made by the user led to problem in the data that were exchange. So I really support this package! 

Now, to the issue, I would like to define custom units that are generic, and allow to assign actual units a posteriori. A concrete example: I am developing a package where distances are measures in pixel units and time in number of frames. These units are very useful, but their actual units depends on a particular setup. So I would like the user to be able to read a file where I setup internally that it is in pixel units. If the user knows the actual length of the pixel, I would like this to automagically propagate.

I could also do that for frames, but I show you with pixel units what I did. I am not sure what the best syntax for this would be, but this is what I wanted to do:
```R
px <- make_unit("px")
len <- runif(5)*px
print(len) # the units are properly set has px
px <- 255*ud_units$nm # so one pixel is 255 nm wide
print(len) # the units are still px. I guess this is expected, even though this would be nice to already have the conversion there
units(len) <- 255*ud_units$nm # throws an error 
```
The error is ```Error in `units<-.units`(`*tmp*`, value = 255) :  cannot convert px into nm``` which, looking at the code is normal because it is executing ```.get_unit_conversion_constant``` that has a FIXME ;) 

For the first way I wanted to assign actual units, maybe one should use a reactive expression. But I guess we should experiment.

Anyway, what do you think?

**Comment by edzer** [comment]
If I understand you correctly, you want to add your own units, and inform the package how they relate to existing units. Right now, this is not possible from within an R script, but it would be nice.

**Comment by grpaulfr** [comment]
Yes, if you wish, like a proxy. One pixel is an arbitrary unit used in image processing, but it actually has a physical scale with SI units.

**Comment by edzer** [comment]
Right now, `units` only allows operations on custom units if they are identical or convertible and part of the `ud_units` structure (or better: be recognized by pkg `udunits2` and its underlying udunits library and database). If we would add a layer on top of that in `units`, it has to be put in global state (e.g. an environment in the package, see [here](https://github.com/edzer/sfr/blob/master/R/init.R#L26-L38) for an example). We could define the conversion constant when creating the unit:
```
px = make_unit("px", 255 * ud_units$nm)
```
but if we'd keep the constant with object `px` rather than in global state, a few steps later you would be able to do
```
py = make_unit("px", 251 * ud_units$nm)
```
which would make the whole thing inconsistent.

**Comment by mailund** [comment]
I have an implementation of user-defined conversion now. It works by the user installing a conversion function between pairs of units, so it is rather general, but the common case where you can go from one unit to another as a linear transformation, *y = a x + b*, there is a function that takes the formula and installs functions for both the conversion *x* to *y* (*y = a x + b*) and the conversion from *y* to *x* (*x = (y - b) / a*).

The code works like this: You install a conversion, for example, you can decide that one orange is worth two apples:

```r
install_conversion_constant("orange", "apple", 2)
```

and after that you can do arithmetic with apples and oranges:

```r
apples <- 2 * make_unit("apple")
oranges <- 3 * make_unit("orange")
apples + oranges
oranges + apples
```

The conversion is, of course, also used when simplifying unit-expressions. User-defined conversions are chosen over `udunit` conversion, and if you want to convert between a user-defined unit and a `udunit` unit, you just need to install the appropriate function.

I'll make a pull-request shortly.

**Comment by xhdong-umd** [comment]
I looked at `units`, `udunits2` and udunits project. There are [C API methods in udunits to add user defined units](https://www.unidata.ucar.edu/software/udunits/udunits-2.0.4/udunits2lib.html#Adding) but they are not mapped in `udunits2`. The most ideal method will be create r wrapper for those API call, create user defined units and add them to the udunits database, then everything will just works, including the conversion and simplifying. 

Of course the problem could also be solved in `units` package, like what @mailund just did.  I'm not sure how @mailund 's new feature work yet, maybe it already solve all the problems. 

I'm wondering if we can still use the syntax like `px = make_unit("px", 255 * ud_units$nm)`. We just need to save a user defined table in global state (either in script scope or package user scope according to usage). We can add one more attribute in units object to indicate the unit is user defined.

**Comment by mailund** [comment]
What I implemented works to a degree, but I haven't figured out how to deal with non-linear transformations in an entirely clean way. Take a look at pull request #31 to see the current status. The problem is not really programming it -- that part works -- it is figuring out such non-linear operations should really behave.
