### ISSUE TITLE
Feature request: engineering notation

### ISSUE THREAD

**Issue by carbonmetrics** [edzer/units#25]
Not included in R, but used all the time, is engineering notation.
This uses SI prefixes (kilo 10E3, Mega 10E6, Giga 10E9, etc).
It is something that you use all the time because it corresponds to normal units you use all the time (meter, kilometer, kg, tonne, etc). 

It would be great if your package could include [Engineering notation](https://en.wikipedia.org/wiki/Engineering_notation) somehow.

**Comment by edzer** [comment]
Do you mean something along these lines:
```
> k_m = make_unit("10^3 m")
> (x <- 1:5 * k_m)
Units: 10^3 m
[1] 1 2 3 4 5
> units(x)  = m
> x
Units: m
[1] 1000 2000 3000 4000 5000
> units(x)  = make_unit("10^9 m")
> x
Units: 10^9 m
[1] 1e-06 2e-06 3e-06 4e-06 5e-06
```
SI prefixes are supported, already.
