### ISSUE TITLE
Error message in misc tests.

### ISSUE THREAD

**Issue by mailund** [edzer/units#30]
I get the error message

```
Error in `units<-.units`(`*tmp*`, value = structure(list(numerator = "m",  : 
  cannot convert s into m
```

when I run the unit tests for misc. It is not an error, as such, the test correctly predicts an error, but the message is a bit annoying. I don't know why we get it, though...

**Comment by edzer** [comment]
You can suppress the call tree by adding arg `.call = FALSE` to a `stop` function call.
