### ISSUE TITLE
ud_units doesn't work when package isn't attached

### ISSUE THREAD

**Issue by hadley** [edzer/units#35]
``` r
1:5 * with(units::ud_units, m/s)
#> Error in eval(expr, envir, enclos): object 'm' not found
```

And I couldn't figure out an easy to create a unit without attaching it.

**Comment by edzer** [comment]
also fixed with https://github.com/edzer/units/commit/a400f0ab182d7c3fc9b50417e14ba8fcb5a91d41

**Comment by edzer** [comment]
This commit didn't make it on Windows, due to the non-ascii units now in R code...
