### ISSUE TITLE
Convenient constructor

### ISSUE THREAD

**Issue by hadley** [edzer/units#36]
I think it would be nice to have a convenient constructor like:

```
unit(100, km / s)
unit(10, m ^ 3)
```

**Comment by edzer** [comment]
I dropped `unit` in favour of `set_units`, because

* we already had `set_units`
* it sets units
* `unit` collides with `grid::unit`, and is not a generic

`set_units` converts units in case its first arg is of class `units`, similar to `units<-`.

**Comment by hadley** [comment]
I think `new_unit()` or `make_unit()` would be slightly more descriptive.

**Comment by edzer** [comment]
We already have `make_unit`, it makes a unit, rather than setting it. See also #22.
```r
apples = make_unit("apples")
set_units(1:5, apples)
# Units: apples
# [1] 1 2 3 4 5
```

**Comment by hadley** [comment]
Most people are not going to create new types of unit, but are going to create vectors labelled with a unit. I think that suggests you should given unit creation functions longer names because they'll be less commonly used
