### ISSUE TITLE
Difficultly installing on CentOS

### ISSUE THREAD

**Issue by olyerickson** [edzer/units#37]
I've gotten this working on Linux Mint 18.1 thanks to the procedure in the README http://bit.ly/2lgyHox but I can't get it working on CentOS 7. 

What is the equivalent system-level magic, using yum? 

Thanks!

**Comment by olyerickson** [comment]
I was able to get this to work...

* udunits2 needed to be properly installed on CentOS, and it's installation directories located, esp. 
```
$ rpm -ql udunits2-devel
/usr/include/udunits2
/usr/include/udunits2/converter.h
/usr/include/udunits2/udunits.h
/usr/include/udunits2/udunits2.h
/usr/lib64/libudunits2.so
```
* Then in R:
```
> install.packages('udunits2', type = 'source', repo = 'cran.rstudio.com', configure.args='--with-udunits2-include=/usr/include/udunits2')
```
Then this:
```
install_github("edzer/units")
```

This then enabled e.g. `ggraph` to be installed without a problem..

**Comment by digital-dharma** [comment]
@olyerickson - Do you recall what steps you followed to install `udunits2` on centOS?  Despite what I believe to be a successful installation, subsequent attempts to install `units` continues to fail with the same error.

I suspect I am installing this dependency at some global level, unrecognized by my user account.

```
** testing if installed package can be loaded
Error: package or namespace load failed for ‘udunits2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/<MY USER>/R/x86_64-redhat-linux-gnu-library/3.4/udunits2/libs/udunits2.so':
  libudunits2.so: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
```

**Comment by enricoferrero** [comment]
@digital-dharma I'm getting the same error, did you find a solution?
CC @olyerickson @edzer

**Comment by edzer** [comment]
Maybe run `sudo ldconfig` after installing the udunits2 library?

**Comment by enricoferrero** [comment]
Unfortunately, I don't have admin rights, but the other solution you proposed worked:
https://github.com/r-quantities/units/issues/1#issuecomment-415690886
