### ISSUE TITLE
units for functions

### ISSUE THREAD

**Issue by ibarraespinosa** [edzer/units#39]
Dear all,

Is it possible to add units to functions? So far I've tried without success:

```
f <- function(V) {3}
f <- f * parse_unit(paste0("g km-1"))
units(f) <- with(ud_units, g/km)
units(f(1)) <- with(ud_units, g/km)

```

**Comment by edzer** [comment]
No, and I also don't understand why you would want to do so.

**Comment by edzer** [comment]
You can:
* set the units of a value before it is returned by a function, or
* propagate the units of a function parameter by its output, but

functions are functions; anything special to them should happen _inside_ the function body.
