### ISSUE TITLE
matrices coerced to vectors

### ISSUE THREAD

**Issue by graemeblair** [edzer/units#47]
Hi there -- love this package. Thanks for all your work on it.

When I use some mathematical operations such as inequalities on units objects that are matrices, the matrices are coerced into vectors.

With multiplication between a matrix and for example a scalar, it works as I expected, resulting in a matrix:

```
> my_matrix <- set_units(cbind(1:3, 4:6), "km")

> my_matrix * set_units(5, "km")
Units: km^2
[,1] [,2]
[1,]    5   20
[2,]   10   25
[3,]   15   30
```

However, when I do the same thing except use an inequality instead of multiplication, a vector results:

```
> my_matrix <= set_units(5, "km")
[1]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
```

Apologies if this has been answered elsewhere!

**Comment by edzer** [comment]
Thanks - should work now!

**Comment by graemeblair** [comment]
Thank you!
