### ISSUE TITLE
Units not printed as inline output in R Markdown documents

### ISSUE THREAD

**Issue by emiltb** [edzer/units#48]
I am trying to use the units package in R Markdown. It would make it very easy to do some calculations and write about the results. For some reason the units are not printed after the numbers in the inline R code. See the example below. I am unsure whether it is a problem with the `print.units()` function (I don't think it is, since it works nicely from the console) or how R Markdown handles printing in inline R code.

    ---
    title: "Units inline problem"
    author: "Emil Tveden Bjerglund"
    date: "9 aug 2017"
    output: html_document
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    library(units)
    ```
    
    We can define things with units, and when called from within a chunk they print as expected.
    
    ```{r}
    v <- set_units(10, m/s)
    t <- set_units(25, s)
    d <- v*t
    d
    ```
    
    But when trying to write about the calculations and pasting in variables (i.e. `r d`) the units are     not printed. Trying to do `r print(d)` prints nothing.

![image](https://user-images.githubusercontent.com/12095920/29120249-bef1225e-7d09-11e7-9caa-52cad7d19839.png)

**Comment by edzer** [comment]
Thanks, I will get back to this in a couple of weeks, when back in the office.

On 9 August 2017 13:53:58 CEST, Emil Bjerglund Pedersen <notifications@github.com> wrote:
>I am trying to use the units package in R Markdown. It would make it
>very easy to do some calculations and write about the results. For some
>reason the units are not printed after the numbers in the inline R
>code. See the example below. I am unsure whether it is a problem with
>the `print.units()` function (I don't think it is, since it works
>nicely from the console) or how R Markdown handles printing in inline R
>code.
>
>    ---
>    title: "Units inline problem"
>    author: "Emil Tveden Bjerglund"
>    date: "9 aug 2017"
>    output: html_document
>    ---
>    
>    ```{r setup, include=FALSE}
>    knitr::opts_chunk$set(echo = TRUE)
>    library(units)
>    ```
>    
>We can define things with units, and when called from within a chunk
>they print as expected.
>    
>    ```{r}
>    v <- set_units(10, m/s)
>    t <- set_units(25, s)
>    d <- v*t
>    d
>    ```
>    
>But when trying to write about the calculations and pasting in
>variables (i.e. `r d`) the units are     not printed. Trying to do `r
>print(d)` prints nothing.
>
>![image](https://user-images.githubusercontent.com/12095920/29120249-bef1225e-7d09-11e7-9caa-52cad7d19839.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/edzer/units/issues/48

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by edzer** [comment]
Try using 

    `r format(d)` 

instead for inline units. I have no clue why the inline `r d` does not work.
