### ISSUE TITLE
incorrect acres to ft^2 conversion

### ISSUE THREAD

**Issue by iembry** [edzer/units#49]
Hi, according to [Units and Symbols Found in the UDUNITS2 Database](https://ncics.org/portfolio/other-resources/udunits2/), an acre is

> unit of area in the US Customary System, used in land and sea floor measurement, equal to 43560 square feet (exact).

If that is true, then the following is incorrect:

```
library(units)

ad <- with(ud_units, 1 * acre)

ad
1 acre


units(ad) <- with(ud_units, ft^2)

ad
43560.17 ft^2
```

If the current definition of acres is incorrect within `units`, then will you correct it then?

Thank you.

Irucka Embry

**Comment by edzer** [comment]
No, if this is an issue, it is an issue with the udunits2 library, found [here](https://github.com/Unidata/UDUNITS-2).

**Comment by iembry** [comment]
Thank you for letting me know. I'll make an issue note there.
