### ISSUE TITLE
FR: as.hms.units()

### ISSUE THREAD

**Issue by krlmlr** [edzer/units#9]
Simply `as.hms.units <- function(x, ...) as.hms(as.dt(x, ...))`, but probably needs to import `hms`.

**Comment by edzer** [comment]
I now realize that `hms` is used for time of day, not duration. The way I implemented simply coerces a `difftime` object (time duration) into a `hms`, but that means something different. I will remove this until we've sorted it out. `udunits` does have support for absolute time; we could coerce that to `POSIXct`, and then drop day and retain a `hms`; the other way around is impossible without knowing the day.

**Comment by krlmlr** [comment]
hms wraps difftime, and so can be used for both: duration (as difference of two times) and time of day (like in `Sys.time() - as.POSIXct(Sys.Date())`).

**Comment by edzer** [comment]
I can see that, but that is not how the hms package explains what hms values mean. So: syntactically yes, semantically no, and measurement units are about meaning. Subclassing time-of-day from a time duration class is a conceptual mistake: is 12:00:00 twice as late as 06:00:00? hms thinks so:
```
> library(hms)
> hms(hours=6)
06:00:00
> hms(hours=6)*2
Time difference of 43200 secs
```
???

**Comment by krlmlr** [comment]
Thanks, I shall adapt the README then. The hms class doesn't specify preferred usage, it's just a container with nice formatting intended to be compatible to difftime.

See rstats-db/hms#18 for the conversion issue.

**Comment by edzer** [comment]
The better fix would be to make `hms` unambiguous (and not derive from `difftime`)

**Comment by edzer** [comment]
O.K., you clarified that the meaning of hms `09:00:00` can be one of
* a duration of 9 hours (since 00:00 midnight)
* 9 o'clock, as of "the shop opens at 9 o'clock in the morning", reflecting time-of-day

Since this cannot be be converted unambiguously in an SI unit of time duration (as package `units` understands them), I close this issue.
